# Makefile for avl.cpp

# Compiler and compiler flags
CXX = g++
CXXFLAGS = -std=c++11

# Target executable
TARGET = avl

# Source file
SRC = avl.cpp

all: $(TARGET)

$(TARGET): $(SRC)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(SRC)

clean:
	rm -f $(TARGET)